//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS_GateCollector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMS_GateCollector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g0 {
            get {
                object obj = ResourceManager.GetObject("g0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g1 {
            get {
                object obj = ResourceManager.GetObject("g1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g2 {
            get {
                object obj = ResourceManager.GetObject("g2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g3 {
            get {
                object obj = ResourceManager.GetObject("g3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g4 {
            get {
                object obj = ResourceManager.GetObject("g4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g5 {
            get {
                object obj = ResourceManager.GetObject("g5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g6 {
            get {
                object obj = ResourceManager.GetObject("g6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g7 {
            get {
                object obj = ResourceManager.GetObject("g7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g8 {
            get {
                object obj = ResourceManager.GetObject("g8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap g9 {
            get {
                object obj = ResourceManager.GetObject("g9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gA {
            get {
                object obj = ResourceManager.GetObject("gA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euclid.
        /// </summary>
        public static string Gal0 {
            get {
                return ResourceManager.GetString("Gal0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilbert Dimension.
        /// </summary>
        public static string Gal1 {
            get {
                return ResourceManager.GetString("Gal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elkupalos.
        /// </summary>
        public static string Gal10 {
            get {
                return ResourceManager.GetString("Gal10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuychelisaor.
        /// </summary>
        public static string Gal100 {
            get {
                return ResourceManager.GetString("Gal100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivskimbe.
        /// </summary>
        public static string Gal101 {
            get {
                return ResourceManager.GetString("Gal101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daksanquix.
        /// </summary>
        public static string Gal102 {
            get {
                return ResourceManager.GetString("Gal102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kissonlin.
        /// </summary>
        public static string Gal103 {
            get {
                return ResourceManager.GetString("Gal103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aediabiel.
        /// </summary>
        public static string Gal104 {
            get {
                return ResourceManager.GetString("Gal104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulosaginyik.
        /// </summary>
        public static string Gal105 {
            get {
                return ResourceManager.GetString("Gal105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roclaytonycar.
        /// </summary>
        public static string Gal106 {
            get {
                return ResourceManager.GetString("Gal106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kichiaroa.
        /// </summary>
        public static string Gal107 {
            get {
                return ResourceManager.GetString("Gal107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irceauffey.
        /// </summary>
        public static string Gal108 {
            get {
                return ResourceManager.GetString("Gal108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudquathsenfe.
        /// </summary>
        public static string Gal109 {
            get {
                return ResourceManager.GetString("Gal109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aptarkaba.
        /// </summary>
        public static string Gal11 {
            get {
                return ResourceManager.GetString("Gal11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getaizakaal.
        /// </summary>
        public static string Gal110 {
            get {
                return ResourceManager.GetString("Gal110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hansolmien.
        /// </summary>
        public static string Gal111 {
            get {
                return ResourceManager.GetString("Gal111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloytisagra.
        /// </summary>
        public static string Gal112 {
            get {
                return ResourceManager.GetString("Gal112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladsenlay.
        /// </summary>
        public static string Gal113 {
            get {
                return ResourceManager.GetString("Gal113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luyugoslasr.
        /// </summary>
        public static string Gal114 {
            get {
                return ResourceManager.GetString("Gal114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubredhatk.
        /// </summary>
        public static string Gal115 {
            get {
                return ResourceManager.GetString("Gal115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidoniana.
        /// </summary>
        public static string Gal116 {
            get {
                return ResourceManager.GetString("Gal116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jasinessa.
        /// </summary>
        public static string Gal117 {
            get {
                return ResourceManager.GetString("Gal117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torweierf.
        /// </summary>
        public static string Gal118 {
            get {
                return ResourceManager.GetString("Gal118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saffneckm.
        /// </summary>
        public static string Gal119 {
            get {
                return ResourceManager.GetString("Gal119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontiniangp.
        /// </summary>
        public static string Gal12 {
            get {
                return ResourceManager.GetString("Gal12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thnistner.
        /// </summary>
        public static string Gal120 {
            get {
                return ResourceManager.GetString("Gal120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotusingg.
        /// </summary>
        public static string Gal121 {
            get {
                return ResourceManager.GetString("Gal121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luleukous.
        /// </summary>
        public static string Gal122 {
            get {
                return ResourceManager.GetString("Gal122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelmandan.
        /// </summary>
        public static string Gal123 {
            get {
                return ResourceManager.GetString("Gal123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otimanaso.
        /// </summary>
        public static string Gal124 {
            get {
                return ResourceManager.GetString("Gal124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjaxusanto.
        /// </summary>
        public static string Gal125 {
            get {
                return ResourceManager.GetString("Gal125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sezviktorew.
        /// </summary>
        public static string Gal126 {
            get {
                return ResourceManager.GetString("Gal126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zikehpm.
        /// </summary>
        public static string Gal127 {
            get {
                return ResourceManager.GetString("Gal127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bephembah.
        /// </summary>
        public static string Gal128 {
            get {
                return ResourceManager.GetString("Gal128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broomerrai.
        /// </summary>
        public static string Gal129 {
            get {
                return ResourceManager.GetString("Gal129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odiwagiri.
        /// </summary>
        public static string Gal13 {
            get {
                return ResourceManager.GetString("Gal13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meximicka.
        /// </summary>
        public static string Gal130 {
            get {
                return ResourceManager.GetString("Gal130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venessika.
        /// </summary>
        public static string Gal131 {
            get {
                return ResourceManager.GetString("Gal131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaiteseling.
        /// </summary>
        public static string Gal132 {
            get {
                return ResourceManager.GetString("Gal132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zosakasiro.
        /// </summary>
        public static string Gal133 {
            get {
                return ResourceManager.GetString("Gal133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drajayanes.
        /// </summary>
        public static string Gal134 {
            get {
                return ResourceManager.GetString("Gal134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooibekuar.
        /// </summary>
        public static string Gal135 {
            get {
                return ResourceManager.GetString("Gal135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urckiansi.
        /// </summary>
        public static string Gal136 {
            get {
                return ResourceManager.GetString("Gal136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dozivadido.
        /// </summary>
        public static string Gal137 {
            get {
                return ResourceManager.GetString("Gal137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emiekereks.
        /// </summary>
        public static string Gal138 {
            get {
                return ResourceManager.GetString("Gal138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meykinunukur.
        /// </summary>
        public static string Gal139 {
            get {
                return ResourceManager.GetString("Gal139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogtialabi.
        /// </summary>
        public static string Gal14 {
            get {
                return ResourceManager.GetString("Gal14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimycuristh.
        /// </summary>
        public static string Gal140 {
            get {
                return ResourceManager.GetString("Gal140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roansfien.
        /// </summary>
        public static string Gal141 {
            get {
                return ResourceManager.GetString("Gal141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isgarmeso.
        /// </summary>
        public static string Gal142 {
            get {
                return ResourceManager.GetString("Gal142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daitibeli.
        /// </summary>
        public static string Gal143 {
            get {
                return ResourceManager.GetString("Gal143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gucuttarik.
        /// </summary>
        public static string Gal144 {
            get {
                return ResourceManager.GetString("Gal144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlaythie.
        /// </summary>
        public static string Gal145 {
            get {
                return ResourceManager.GetString("Gal145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drewweste.
        /// </summary>
        public static string Gal146 {
            get {
                return ResourceManager.GetString("Gal146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akbulkabi.
        /// </summary>
        public static string Gal147 {
            get {
                return ResourceManager.GetString("Gal147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homskiw.
        /// </summary>
        public static string Gal148 {
            get {
                return ResourceManager.GetString("Gal148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavainlani.
        /// </summary>
        public static string Gal149 {
            get {
                return ResourceManager.GetString("Gal149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muhacksonto.
        /// </summary>
        public static string Gal15 {
            get {
                return ResourceManager.GetString("Gal15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewijkmas.
        /// </summary>
        public static string Gal150 {
            get {
                return ResourceManager.GetString("Gal150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itlhotagra.
        /// </summary>
        public static string Gal151 {
            get {
                return ResourceManager.GetString("Gal151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podalicess.
        /// </summary>
        public static string Gal152 {
            get {
                return ResourceManager.GetString("Gal152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiviusauer.
        /// </summary>
        public static string Gal153 {
            get {
                return ResourceManager.GetString("Gal153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halsebenk.
        /// </summary>
        public static string Gal154 {
            get {
                return ResourceManager.GetString("Gal154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puikitoac.
        /// </summary>
        public static string Gal155 {
            get {
                return ResourceManager.GetString("Gal155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaybakuaria.
        /// </summary>
        public static string Gal156 {
            get {
                return ResourceManager.GetString("Gal156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grbodubhe.
        /// </summary>
        public static string Gal157 {
            get {
                return ResourceManager.GetString("Gal157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rycempler.
        /// </summary>
        public static string Gal158 {
            get {
                return ResourceManager.GetString("Gal158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indjalala.
        /// </summary>
        public static string Gal159 {
            get {
                return ResourceManager.GetString("Gal159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitonskyer.
        /// </summary>
        public static string Gal16 {
            get {
                return ResourceManager.GetString("Gal16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fontenikk.
        /// </summary>
        public static string Gal160 {
            get {
                return ResourceManager.GetString("Gal160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasycihelwhee.
        /// </summary>
        public static string Gal161 {
            get {
                return ResourceManager.GetString("Gal161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikbaksmit.
        /// </summary>
        public static string Gal162 {
            get {
                return ResourceManager.GetString("Gal162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telicianses.
        /// </summary>
        public static string Gal163 {
            get {
                return ResourceManager.GetString("Gal163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyleyzhan.
        /// </summary>
        public static string Gal164 {
            get {
                return ResourceManager.GetString("Gal164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uagerosat.
        /// </summary>
        public static string Gal165 {
            get {
                return ResourceManager.GetString("Gal165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impoxectin.
        /// </summary>
        public static string Gal166 {
            get {
                return ResourceManager.GetString("Gal166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoodmand.
        /// </summary>
        public static string Gal167 {
            get {
                return ResourceManager.GetString("Gal167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfsesorbs.
        /// </summary>
        public static string Gal168 {
            get {
                return ResourceManager.GetString("Gal168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezdaranit.
        /// </summary>
        public static string Gal169 {
            get {
                return ResourceManager.GetString("Gal169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerasmutul.
        /// </summary>
        public static string Gal17 {
            get {
                return ResourceManager.GetString("Gal17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiensanshe.
        /// </summary>
        public static string Gal170 {
            get {
                return ResourceManager.GetString("Gal170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ewheelonc.
        /// </summary>
        public static string Gal171 {
            get {
                return ResourceManager.GetString("Gal171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litzmantufa.
        /// </summary>
        public static string Gal172 {
            get {
                return ResourceManager.GetString("Gal172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emarmatosi.
        /// </summary>
        public static string Gal173 {
            get {
                return ResourceManager.GetString("Gal173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mufimbomacvi.
        /// </summary>
        public static string Gal174 {
            get {
                return ResourceManager.GetString("Gal174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wongquarum.
        /// </summary>
        public static string Gal175 {
            get {
                return ResourceManager.GetString("Gal175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapirajua.
        /// </summary>
        public static string Gal176 {
            get {
                return ResourceManager.GetString("Gal176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igbinduina.
        /// </summary>
        public static string Gal177 {
            get {
                return ResourceManager.GetString("Gal177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wepaitvas.
        /// </summary>
        public static string Gal178 {
            get {
                return ResourceManager.GetString("Gal178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sthatigudi.
        /// </summary>
        public static string Gal179 {
            get {
                return ResourceManager.GetString("Gal179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isdoraijung.
        /// </summary>
        public static string Gal18 {
            get {
                return ResourceManager.GetString("Gal18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yekathsebehn.
        /// </summary>
        public static string Gal180 {
            get {
                return ResourceManager.GetString("Gal180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebedeagurst.
        /// </summary>
        public static string Gal181 {
            get {
                return ResourceManager.GetString("Gal181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nolisonia.
        /// </summary>
        public static string Gal182 {
            get {
                return ResourceManager.GetString("Gal182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulexovitab.
        /// </summary>
        public static string Gal183 {
            get {
                return ResourceManager.GetString("Gal183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iodhinxois.
        /// </summary>
        public static string Gal184 {
            get {
                return ResourceManager.GetString("Gal184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irroswitzs.
        /// </summary>
        public static string Gal185 {
            get {
                return ResourceManager.GetString("Gal185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bifredait.
        /// </summary>
        public static string Gal186 {
            get {
                return ResourceManager.GetString("Gal186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beiraghedwe.
        /// </summary>
        public static string Gal187 {
            get {
                return ResourceManager.GetString("Gal187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeonatlak.
        /// </summary>
        public static string Gal188 {
            get {
                return ResourceManager.GetString("Gal188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cugnatachh.
        /// </summary>
        public static string Gal189 {
            get {
                return ResourceManager.GetString("Gal189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctinawyra.
        /// </summary>
        public static string Gal19 {
            get {
                return ResourceManager.GetString("Gal19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozoryenki.
        /// </summary>
        public static string Gal190 {
            get {
                return ResourceManager.GetString("Gal190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebralduri.
        /// </summary>
        public static string Gal191 {
            get {
                return ResourceManager.GetString("Gal191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evcickcandj.
        /// </summary>
        public static string Gal192 {
            get {
                return ResourceManager.GetString("Gal192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziybosswin.
        /// </summary>
        public static string Gal193 {
            get {
                return ResourceManager.GetString("Gal193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heperclait.
        /// </summary>
        public static string Gal194 {
            get {
                return ResourceManager.GetString("Gal194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugiuniam.
        /// </summary>
        public static string Gal195 {
            get {
                return ResourceManager.GetString("Gal195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaseertush.
        /// </summary>
        public static string Gal196 {
            get {
                return ResourceManager.GetString("Gal196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uglyestemaa.
        /// </summary>
        public static string Gal197 {
            get {
                return ResourceManager.GetString("Gal197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horeroedsh.
        /// </summary>
        public static string Gal198 {
            get {
                return ResourceManager.GetString("Gal198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drundemiso.
        /// </summary>
        public static string Gal199 {
            get {
                return ResourceManager.GetString("Gal199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calypso.
        /// </summary>
        public static string Gal2 {
            get {
                return ResourceManager.GetString("Gal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loychazinq.
        /// </summary>
        public static string Gal20 {
            get {
                return ResourceManager.GetString("Gal20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ityanianat.
        /// </summary>
        public static string Gal200 {
            get {
                return ResourceManager.GetString("Gal200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purneyrine.
        /// </summary>
        public static string Gal201 {
            get {
                return ResourceManager.GetString("Gal201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokiessmat.
        /// </summary>
        public static string Gal202 {
            get {
                return ResourceManager.GetString("Gal202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nupiacheh.
        /// </summary>
        public static string Gal203 {
            get {
                return ResourceManager.GetString("Gal203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dihewsonj.
        /// </summary>
        public static string Gal204 {
            get {
                return ResourceManager.GetString("Gal204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rudrailhik.
        /// </summary>
        public static string Gal205 {
            get {
                return ResourceManager.GetString("Gal205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweretnort.
        /// </summary>
        public static string Gal206 {
            get {
                return ResourceManager.GetString("Gal206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snatreetze.
        /// </summary>
        public static string Gal207 {
            get {
                return ResourceManager.GetString("Gal207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iwunddaracos.
        /// </summary>
        public static string Gal208 {
            get {
                return ResourceManager.GetString("Gal208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digarlewena.
        /// </summary>
        public static string Gal209 {
            get {
                return ResourceManager.GetString("Gal209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zukasizawa.
        /// </summary>
        public static string Gal21 {
            get {
                return ResourceManager.GetString("Gal21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erquagsta.
        /// </summary>
        public static string Gal210 {
            get {
                return ResourceManager.GetString("Gal210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logovoloin.
        /// </summary>
        public static string Gal211 {
            get {
                return ResourceManager.GetString("Gal211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boyaghosganh.
        /// </summary>
        public static string Gal212 {
            get {
                return ResourceManager.GetString("Gal212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuolungau.
        /// </summary>
        public static string Gal213 {
            get {
                return ResourceManager.GetString("Gal213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pehneldept.
        /// </summary>
        public static string Gal214 {
            get {
                return ResourceManager.GetString("Gal214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yevettiiqidcon.
        /// </summary>
        public static string Gal215 {
            get {
                return ResourceManager.GetString("Gal215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahliacabru.
        /// </summary>
        public static string Gal216 {
            get {
                return ResourceManager.GetString("Gal216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noggalterpor.
        /// </summary>
        public static string Gal217 {
            get {
                return ResourceManager.GetString("Gal217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chmageaki.
        /// </summary>
        public static string Gal218 {
            get {
                return ResourceManager.GetString("Gal218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veticueca.
        /// </summary>
        public static string Gal219 {
            get {
                return ResourceManager.GetString("Gal219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekwathore.
        /// </summary>
        public static string Gal22 {
            get {
                return ResourceManager.GetString("Gal22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vittesbursul.
        /// </summary>
        public static string Gal220 {
            get {
                return ResourceManager.GetString("Gal220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nootanore.
        /// </summary>
        public static string Gal221 {
            get {
                return ResourceManager.GetString("Gal221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innebdjerah.
        /// </summary>
        public static string Gal222 {
            get {
                return ResourceManager.GetString("Gal222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kisvarcini.
        /// </summary>
        public static string Gal223 {
            get {
                return ResourceManager.GetString("Gal223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuzcogipper.
        /// </summary>
        public static string Gal224 {
            get {
                return ResourceManager.GetString("Gal224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamanhermonsu.
        /// </summary>
        public static string Gal225 {
            get {
                return ResourceManager.GetString("Gal225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brotoghek.
        /// </summary>
        public static string Gal226 {
            get {
                return ResourceManager.GetString("Gal226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mibittara.
        /// </summary>
        public static string Gal227 {
            get {
                return ResourceManager.GetString("Gal227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huruahili.
        /// </summary>
        public static string Gal228 {
            get {
                return ResourceManager.GetString("Gal228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raldwicarn.
        /// </summary>
        public static string Gal229 {
            get {
                return ResourceManager.GetString("Gal229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeberhahne.
        /// </summary>
        public static string Gal23 {
            get {
                return ResourceManager.GetString("Gal23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezdartlic.
        /// </summary>
        public static string Gal230 {
            get {
                return ResourceManager.GetString("Gal230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badesclema.
        /// </summary>
        public static string Gal231 {
            get {
                return ResourceManager.GetString("Gal231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isenkeyan.
        /// </summary>
        public static string Gal232 {
            get {
                return ResourceManager.GetString("Gal232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iadoitesu.
        /// </summary>
        public static string Gal233 {
            get {
                return ResourceManager.GetString("Gal233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yagrovoisi.
        /// </summary>
        public static string Gal234 {
            get {
                return ResourceManager.GetString("Gal234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ewcomechio.
        /// </summary>
        public static string Gal235 {
            get {
                return ResourceManager.GetString("Gal235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inunnunnoda.
        /// </summary>
        public static string Gal236 {
            get {
                return ResourceManager.GetString("Gal236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dischiutun.
        /// </summary>
        public static string Gal237 {
            get {
                return ResourceManager.GetString("Gal237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuwarugha.
        /// </summary>
        public static string Gal238 {
            get {
                return ResourceManager.GetString("Gal238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ialmendra.
        /// </summary>
        public static string Gal239 {
            get {
                return ResourceManager.GetString("Gal239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twerbetek.
        /// </summary>
        public static string Gal24 {
            get {
                return ResourceManager.GetString("Gal24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reponudrle.
        /// </summary>
        public static string Gal240 {
            get {
                return ResourceManager.GetString("Gal240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rinjanagrbo.
        /// </summary>
        public static string Gal241 {
            get {
                return ResourceManager.GetString("Gal241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeziceloh.
        /// </summary>
        public static string Gal242 {
            get {
                return ResourceManager.GetString("Gal242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeileutasc.
        /// </summary>
        public static string Gal243 {
            get {
                return ResourceManager.GetString("Gal243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zicniijinis.
        /// </summary>
        public static string Gal244 {
            get {
                return ResourceManager.GetString("Gal244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dugnowarilda.
        /// </summary>
        public static string Gal245 {
            get {
                return ResourceManager.GetString("Gal245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuxoisan.
        /// </summary>
        public static string Gal246 {
            get {
                return ResourceManager.GetString("Gal246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilmenhorn.
        /// </summary>
        public static string Gal247 {
            get {
                return ResourceManager.GetString("Gal247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rukwatsuku.
        /// </summary>
        public static string Gal248 {
            get {
                return ResourceManager.GetString("Gal248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepitzaspru.
        /// </summary>
        public static string Gal249 {
            get {
                return ResourceManager.GetString("Gal249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sivarates.
        /// </summary>
        public static string Gal25 {
            get {
                return ResourceManager.GetString("Gal25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcehoemig.
        /// </summary>
        public static string Gal250 {
            get {
                return ResourceManager.GetString("Gal250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haffneyrin.
        /// </summary>
        public static string Gal251 {
            get {
                return ResourceManager.GetString("Gal251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uliciawai.
        /// </summary>
        public static string Gal252 {
            get {
                return ResourceManager.GetString("Gal252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuhgrespod.
        /// </summary>
        public static string Gal253 {
            get {
                return ResourceManager.GetString("Gal253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iousongola.
        /// </summary>
        public static string Gal254 {
            get {
                return ResourceManager.GetString("Gal254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odyalutai.
        /// </summary>
        public static string Gal255 {
            get {
                return ResourceManager.GetString("Gal255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eajerandal.
        /// </summary>
        public static string Gal26 {
            get {
                return ResourceManager.GetString("Gal26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aldukesci.
        /// </summary>
        public static string Gal27 {
            get {
                return ResourceManager.GetString("Gal27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wotyarogii.
        /// </summary>
        public static string Gal28 {
            get {
                return ResourceManager.GetString("Gal28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudzerbal.
        /// </summary>
        public static string Gal29 {
            get {
                return ResourceManager.GetString("Gal29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesperius Dimension.
        /// </summary>
        public static string Gal3 {
            get {
                return ResourceManager.GetString("Gal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maupenzhay.
        /// </summary>
        public static string Gal30 {
            get {
                return ResourceManager.GetString("Gal30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugueziume.
        /// </summary>
        public static string Gal31 {
            get {
                return ResourceManager.GetString("Gal31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brogoweldian.
        /// </summary>
        public static string Gal32 {
            get {
                return ResourceManager.GetString("Gal32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehbogdenbu.
        /// </summary>
        public static string Gal33 {
            get {
                return ResourceManager.GetString("Gal33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ijsenufryos.
        /// </summary>
        public static string Gal34 {
            get {
                return ResourceManager.GetString("Gal34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nipikulha.
        /// </summary>
        public static string Gal35 {
            get {
                return ResourceManager.GetString("Gal35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autsurabin.
        /// </summary>
        public static string Gal36 {
            get {
                return ResourceManager.GetString("Gal36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lusontrygiamh.
        /// </summary>
        public static string Gal37 {
            get {
                return ResourceManager.GetString("Gal37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewmanawa.
        /// </summary>
        public static string Gal38 {
            get {
                return ResourceManager.GetString("Gal38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiophodhe.
        /// </summary>
        public static string Gal39 {
            get {
                return ResourceManager.GetString("Gal39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyades.
        /// </summary>
        public static string Gal4 {
            get {
                return ResourceManager.GetString("Gal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urastrykle.
        /// </summary>
        public static string Gal40 {
            get {
                return ResourceManager.GetString("Gal40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xobeurindj.
        /// </summary>
        public static string Gal41 {
            get {
                return ResourceManager.GetString("Gal41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oniijialdu.
        /// </summary>
        public static string Gal42 {
            get {
                return ResourceManager.GetString("Gal42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wucetosucc.
        /// </summary>
        public static string Gal43 {
            get {
                return ResourceManager.GetString("Gal43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebyeloofdud.
        /// </summary>
        public static string Gal44 {
            get {
                return ResourceManager.GetString("Gal44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odyavanta.
        /// </summary>
        public static string Gal45 {
            get {
                return ResourceManager.GetString("Gal45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milekistri.
        /// </summary>
        public static string Gal46 {
            get {
                return ResourceManager.GetString("Gal46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waferganh.
        /// </summary>
        public static string Gal47 {
            get {
                return ResourceManager.GetString("Gal47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agnusopwit.
        /// </summary>
        public static string Gal48 {
            get {
                return ResourceManager.GetString("Gal48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teyaypilny.
        /// </summary>
        public static string Gal49 {
            get {
                return ResourceManager.GetString("Gal49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ickjamatew.
        /// </summary>
        public static string Gal5 {
            get {
                return ResourceManager.GetString("Gal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalienkosm.
        /// </summary>
        public static string Gal50 {
            get {
                return ResourceManager.GetString("Gal50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladgudiraf.
        /// </summary>
        public static string Gal51 {
            get {
                return ResourceManager.GetString("Gal51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushonponte.
        /// </summary>
        public static string Gal52 {
            get {
                return ResourceManager.GetString("Gal52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amsentisz.
        /// </summary>
        public static string Gal53 {
            get {
                return ResourceManager.GetString("Gal53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fladiselm.
        /// </summary>
        public static string Gal54 {
            get {
                return ResourceManager.GetString("Gal54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laanawemb.
        /// </summary>
        public static string Gal55 {
            get {
                return ResourceManager.GetString("Gal55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilkerloor.
        /// </summary>
        public static string Gal56 {
            get {
                return ResourceManager.GetString("Gal56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davanossi.
        /// </summary>
        public static string Gal57 {
            get {
                return ResourceManager.GetString("Gal57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ploehrliou.
        /// </summary>
        public static string Gal58 {
            get {
                return ResourceManager.GetString("Gal58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpinyaya.
        /// </summary>
        public static string Gal59 {
            get {
                return ResourceManager.GetString("Gal59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budullangr.
        /// </summary>
        public static string Gal6 {
            get {
                return ResourceManager.GetString("Gal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leckandmeram.
        /// </summary>
        public static string Gal60 {
            get {
                return ResourceManager.GetString("Gal60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quulngais.
        /// </summary>
        public static string Gal61 {
            get {
                return ResourceManager.GetString("Gal61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokokipsechl.
        /// </summary>
        public static string Gal62 {
            get {
                return ResourceManager.GetString("Gal62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rinblodesa.
        /// </summary>
        public static string Gal63 {
            get {
                return ResourceManager.GetString("Gal63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loydporpen.
        /// </summary>
        public static string Gal64 {
            get {
                return ResourceManager.GetString("Gal64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibtrevskip.
        /// </summary>
        public static string Gal65 {
            get {
                return ResourceManager.GetString("Gal65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elkowaldb.
        /// </summary>
        public static string Gal66 {
            get {
                return ResourceManager.GetString("Gal66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heholhofsko.
        /// </summary>
        public static string Gal67 {
            get {
                return ResourceManager.GetString("Gal67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yebrilowisod.
        /// </summary>
        public static string Gal68 {
            get {
                return ResourceManager.GetString("Gal68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husalvangewi.
        /// </summary>
        public static string Gal69 {
            get {
                return ResourceManager.GetString("Gal69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kikolgallr.
        /// </summary>
        public static string Gal7 {
            get {
                return ResourceManager.GetString("Gal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovna&apos;uesed.
        /// </summary>
        public static string Gal70 {
            get {
                return ResourceManager.GetString("Gal70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahibusey.
        /// </summary>
        public static string Gal71 {
            get {
                return ResourceManager.GetString("Gal71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuybeliaure.
        /// </summary>
        public static string Gal72 {
            get {
                return ResourceManager.GetString("Gal72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doshawchuc.
        /// </summary>
        public static string Gal73 {
            get {
                return ResourceManager.GetString("Gal73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruckinarkh.
        /// </summary>
        public static string Gal74 {
            get {
                return ResourceManager.GetString("Gal74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thorettac.
        /// </summary>
        public static string Gal75 {
            get {
                return ResourceManager.GetString("Gal75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuponoparau.
        /// </summary>
        public static string Gal76 {
            get {
                return ResourceManager.GetString("Gal76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moglaschil.
        /// </summary>
        public static string Gal77 {
            get {
                return ResourceManager.GetString("Gal77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uiweupose.
        /// </summary>
        public static string Gal78 {
            get {
                return ResourceManager.GetString("Gal78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasmilete.
        /// </summary>
        public static string Gal79 {
            get {
                return ResourceManager.GetString("Gal79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eltiensleen.
        /// </summary>
        public static string Gal8 {
            get {
                return ResourceManager.GetString("Gal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekdaluskin.
        /// </summary>
        public static string Gal80 {
            get {
                return ResourceManager.GetString("Gal80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakapanasy.
        /// </summary>
        public static string Gal81 {
            get {
                return ResourceManager.GetString("Gal81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimonimba.
        /// </summary>
        public static string Gal82 {
            get {
                return ResourceManager.GetString("Gal82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajaccari.
        /// </summary>
        public static string Gal83 {
            get {
                return ResourceManager.GetString("Gal83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olonerovo.
        /// </summary>
        public static string Gal84 {
            get {
                return ResourceManager.GetString("Gal84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umlanswick.
        /// </summary>
        public static string Gal85 {
            get {
                return ResourceManager.GetString("Gal85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henayliszm.
        /// </summary>
        public static string Gal86 {
            get {
                return ResourceManager.GetString("Gal86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utzenmate.
        /// </summary>
        public static string Gal87 {
            get {
                return ResourceManager.GetString("Gal87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umirpaiya.
        /// </summary>
        public static string Gal88 {
            get {
                return ResourceManager.GetString("Gal88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paholiang.
        /// </summary>
        public static string Gal89 {
            get {
                return ResourceManager.GetString("Gal89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eissentam.
        /// </summary>
        public static string Gal9 {
            get {
                return ResourceManager.GetString("Gal9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iaereznika.
        /// </summary>
        public static string Gal90 {
            get {
                return ResourceManager.GetString("Gal90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yudukagath.
        /// </summary>
        public static string Gal91 {
            get {
                return ResourceManager.GetString("Gal91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boealalosnj.
        /// </summary>
        public static string Gal92 {
            get {
                return ResourceManager.GetString("Gal92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaevarcko.
        /// </summary>
        public static string Gal93 {
            get {
                return ResourceManager.GetString("Gal93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coellosipp.
        /// </summary>
        public static string Gal94 {
            get {
                return ResourceManager.GetString("Gal94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wayndohalou.
        /// </summary>
        public static string Gal95 {
            get {
                return ResourceManager.GetString("Gal95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoduraykl.
        /// </summary>
        public static string Gal96 {
            get {
                return ResourceManager.GetString("Gal96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apmaneessu.
        /// </summary>
        public static string Gal97 {
            get {
                return ResourceManager.GetString("Gal97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hicanpaav.
        /// </summary>
        public static string Gal98 {
            get {
                return ResourceManager.GetString("Gal98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akvasanta.
        /// </summary>
        public static string Gal99 {
            get {
                return ResourceManager.GetString("Gal99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gB {
            get {
                object obj = ResourceManager.GetObject("gB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gC {
            get {
                object obj = ResourceManager.GetObject("gC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gD {
            get {
                object obj = ResourceManager.GetObject("gD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gE {
            get {
                object obj = ResourceManager.GetObject("gE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gF {
            get {
                object obj = ResourceManager.GetObject("gF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
